// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6_9-8_WQ8YKxo4NvTYanO8c2dwXjEWA',
    appId: '1:532491130377:web:598733f141bcb88f80cad8',
    messagingSenderId: '532491130377',
    projectId: 'bite-buddy-79b9c',
    authDomain: 'bite-buddy-79b9c.firebaseapp.com',
    storageBucket: 'bite-buddy-79b9c.firebasestorage.app',
    measurementId: 'G-TWTMGS64LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoUjTMhxjUruNlXYHwPaERbmE94EBPniQ',
    appId: '1:532491130377:android:bdbb8159d610027e80cad8',
    messagingSenderId: '532491130377',
    projectId: 'bite-buddy-79b9c',
    storageBucket: 'bite-buddy-79b9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_TMLDU-C6jLlKaWKfCRHh_lMA5gTfmo0',
    appId: '1:532491130377:ios:a7050ba2c3c66f3280cad8',
    messagingSenderId: '532491130377',
    projectId: 'bite-buddy-79b9c',
    storageBucket: 'bite-buddy-79b9c.firebasestorage.app',
    iosClientId: '532491130377-ci87at72kn4tacvia8em4qav8oct2q1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitebuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_TMLDU-C6jLlKaWKfCRHh_lMA5gTfmo0',
    appId: '1:532491130377:ios:a7050ba2c3c66f3280cad8',
    messagingSenderId: '532491130377',
    projectId: 'bite-buddy-79b9c',
    storageBucket: 'bite-buddy-79b9c.firebasestorage.app',
    iosClientId: '532491130377-ci87at72kn4tacvia8em4qav8oct2q1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitebuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-6_9-8_WQ8YKxo4NvTYanO8c2dwXjEWA',
    appId: '1:532491130377:web:9253d5275ecb315280cad8',
    messagingSenderId: '532491130377',
    projectId: 'bite-buddy-79b9c',
    authDomain: 'bite-buddy-79b9c.firebaseapp.com',
    storageBucket: 'bite-buddy-79b9c.firebasestorage.app',
    measurementId: 'G-RMBWRCHB15',
  );
}
